from __future__ import annotations

from collections import Counter
from pathlib import Path
import re


ISSUE_FILE_NAME = "issue_pending_review.md"


def search_references(
    references: list[dict],
    query: str = "",
    topics: list[str] | None = None,
    limit: int | None = None,
) -> list[dict]:
    query_terms = tokenize(query)
    topic_terms = [topic.lower() for topic in topics or []]
    if not query_terms and not topic_terms:
        return references[:limit] if limit else references

    scored: list[tuple[int, dict]] = []
    for reference in references:
        score = 0
        for term in query_terms:
            score += score_term(reference, term)
        for topic in topic_terms:
            score += score_topic(reference, topic)
        if score:
            scored.append((score, reference))

    ranked = [reference for _, reference in sorted(scored, key=lambda item: (-item[0], item[1]["title"]))]
    return ranked[:limit] if limit else ranked


def answer_architecture_question(question: str, references: list[dict], limit: int = 5) -> str:
    matches = search_references(references, question, limit=limit)
    if not question.strip():
        return "Enter an architecture question to search the AWS reference library."
    if not matches:
        return "No matching AWS architecture references were found. Try adding AWS service names, control themes, or pattern keywords."

    answer_lines = [
        "### Architecture Reference Answer",
        synthesize_answer(question, matches),
        "",
        "### Supporting References",
    ]
    for reference in matches:
        guidance = reference.get("architecture_guidance", [])[:2]
        patterns = reference.get("implementation_patterns", [])[:1]
        evidence = guidance or patterns or [reference.get("summary", "")]
        answer_lines.append(f"- [{reference['title']}]({reference['file_path']}): {evidence[0]}")

    controls = sorted({control for reference in matches for control in reference.get("related_controls", [])})
    services = sorted({service for reference in matches for service in reference.get("aws_services", [])})
    if services:
        answer_lines.extend(["", f"**AWS services surfaced:** {', '.join(services[:10])}"])
    if controls:
        answer_lines.append(f"**Control themes surfaced:** {', '.join(controls[:10])}")
    return "\n".join(answer_lines)


def review_references(references: list[dict]) -> list[dict]:
    issues: list[dict] = []
    for reference in references:
        reasons = questionable_reasons(reference)
        if reasons:
            issues.append(
                {
                    "title": reference["title"],
                    "file_path": reference["file_path"],
                    "source": reference.get("source", ""),
                    "reasons": reasons,
                }
            )
    return sorted(issues, key=lambda item: (item["file_path"], item["title"]))


def write_pending_review(references: list[dict], output_path: Path) -> int:
    issues = review_references(references)
    lines = [
        "# AWS Reference Architecture Issues Pending Review",
        "",
        "Generated by the AWS reference knowledge agent. Review these files before treating them as reusable architecture reference patterns.",
        "",
        "| Source file | Source | Review flag |",
        "| --- | --- | --- |",
    ]
    for issue in issues:
        link = Path(issue["file_path"]).name
        source = issue["source"] or "unknown"
        reason = "<br>".join(issue["reasons"])
        lines.append(f"| [{issue['title']}]({link}) | {source} | {reason} |")
    if not issues:
        lines.append("| No issues flagged | n/a | n/a |")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(issues)


def topic_suggestions(references: list[dict], limit: int = 24) -> list[str]:
    values: list[str] = []
    for reference in references:
        values.extend(reference.get("topics", []))
        values.extend(reference.get("use_cases", []))
        values.extend(reference.get("aws_services", []))
        values.extend(reference.get("related_controls", []))
        if reference.get("aws_family"):
            values.append(reference["aws_family"].replace("_", " "))
    counts = Counter(value for value in values if value)
    return [value for value, _ in counts.most_common(limit)]


def build_search_text(reference: dict) -> str:
    fields = [
        reference.get("title", ""),
        reference.get("summary", ""),
        reference.get("pattern_summary", ""),
        reference.get("scenario", ""),
        reference.get("aws_family", ""),
        reference.get("file_path", ""),
        " ".join(reference.get("topics", [])),
        " ".join(reference.get("use_cases", [])),
        " ".join(reference.get("aws_services", [])),
        " ".join(reference.get("related_controls", [])),
        " ".join(reference.get("implementation_patterns", [])),
        " ".join(reference.get("architecture_guidance", [])),
        " ".join(reference.get("anti_patterns", [])),
    ]
    return " ".join(fields).lower()


def score_term(reference: dict, term: str) -> int:
    weighted_fields = [
        ("title", [reference.get("title", "")], 30),
        ("topics", reference.get("topics", []), 24),
        ("use_cases", reference.get("use_cases", []), 22),
        ("aws_services", reference.get("aws_services", []), 20),
        ("related_controls", reference.get("related_controls", []), 18),
        ("aws_family", [reference.get("aws_family", "")], 16),
        ("pattern_summary", [reference.get("pattern_summary", "")], 12),
        ("implementation_patterns", reference.get("implementation_patterns", []), 8),
        ("architecture_guidance", reference.get("architecture_guidance", []), 6),
        ("scenario", [reference.get("scenario", "")], 4),
        ("file_path", [reference.get("file_path", "")], 2),
    ]
    score = 0
    for _, values, weight in weighted_fields:
        for value in values:
            normalized = value.lower().replace("_", " ").replace("-", " ")
            compact = value.lower()
            if term == normalized or term == compact:
                score += weight * 2
            elif term in normalized or term in compact:
                score += weight
    score += build_search_text(reference).count(term)
    return score


def score_topic(reference: dict, topic: str) -> int:
    normalized_topic = topic.lower().replace("_", " ").replace("-", " ")
    score = 0
    for value in reference.get("topics", []):
        if normalized_topic in value.lower().replace("_", " ").replace("-", " "):
            score += 30
    for value in reference.get("use_cases", []):
        if normalized_topic in value.lower().replace("_", " ").replace("-", " "):
            score += 26
    if normalized_topic in reference.get("aws_family", "").lower().replace("_", " "):
        score += 20
    if any(normalized_topic in service.lower().replace("_", " ") for service in reference.get("aws_services", [])):
        score += 18
    if any(normalized_topic in control.lower().replace("_", " ") for control in reference.get("related_controls", [])):
        score += 16
    if normalized_topic in build_search_text(reference):
        score += 4
    return score


def tokenize(value: str) -> list[str]:
    return [token for token in re.findall(r"[a-z0-9][a-z0-9_-]*", value.lower()) if len(token) > 1]


def synthesize_answer(question: str, matches: list[dict]) -> str:
    top = matches[0]
    families = sorted({reference.get("aws_family", "").replace("_", " ") for reference in matches if reference.get("aws_family")})
    guidance = [item for reference in matches for item in reference.get("architecture_guidance", [])]
    patterns = [item for reference in matches for item in reference.get("implementation_patterns", [])]
    evidence = guidance[:3] or patterns[:3]
    if not evidence:
        return f"The closest match is **{top['title']}**. Use the linked reference notes to validate the implementation details."

    family_text = f" The strongest matching pattern families are {', '.join(families[:3])}." if families else ""
    bullets = "\n".join(f"- {item}" for item in evidence)
    return f"For this question, start with **{top['title']}** and compare it with the adjacent references below.{family_text}\n\n{bullets}"


def questionable_reasons(reference: dict) -> list[str]:
    reasons: list[str] = []
    title = reference.get("title", "").lower()
    guidance = reference.get("architecture_guidance", [])
    implementation_patterns = reference.get("implementation_patterns", [])
    anti_patterns = reference.get("anti_patterns", [])

    if re.search(r"^\d+:\s*implementation patterns$", title):
        reasons.append("Title is generic and does not describe the architecture topic.")
    if len(guidance) < 2:
        reasons.append("Architecture guidance is sparse; needs review for reusable pattern quality.")
    if not implementation_patterns:
        reasons.append("No common implementation pattern was parsed.")
    if not reference.get("aws_services"):
        reasons.append("No AWS service was detected from the content.")
    if any("..." in item or item.rstrip().endswith("because you") for item in anti_patterns):
        reasons.append("Anti-pattern rationale appears truncated or mechanically generated.")
    if "implementation_patterns" == reference.get("aws_family"):
        reasons.append("Pattern family could not be classified beyond generic implementation patterns.")
    return reasons
